server:
  port: 8002
spring:
  application:
    name: lmhy-demo-consumer
  dubbo:
    appname: lmhy-demo-consumer
    protocol: dubbo
    port: 12345
    registry: zookeeper://127.0.0.1:2181
