server:
  port: 8001
spring:
  application:
    name: lmhy-demo-provider
  dubbo:
    appname: lmhy-demo-provider
    protocol: dubbo
    port: 12345
    registry: zookeeper://127.0.0.1:2181
logging:
  level: debug
